app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest_auth:
    resource: "@AppBundle/Controller/Api/AuthApiController.php"
    type:     rest
    prefix:   /api
